### ISSUE TITLE
Please add cl-env

### ISSUE THREAD

**Issue by mini-eggs** [quicklisp/quicklisp-projects#1477]
Source can be found [here](https://github.com/mini-eggs/cl-env). Very small lib. Used to read .env files into environment variables.

New to Common Lisp and esp. Quicklisp/ASDF, any guidance here is appreciated

**Comment by quicklisp** [comment]
It's not clear to me what the project is for. What's an .env file? What format do they use? What effect does INIT have?

It's better to use `with-open-file` instead of `open` and `close`, because any errors in reading will automatically close the file before the debugger takes over. To do otherwise risks leaking open files.

**Comment by mini-eggs** [comment]
Hey! Thanks for the info on `with-open-fiile`. I've made changes to the source code. Included some simple unit tests as well.

I'm familiar with developing/testing/deploying web servers using node/js/php where it's common to keep third part access tokens/keys/whatever you don't want to put in versioning in .env files.

This is basically a port of the js lib [dotenv](https://www.npmjs.com/package/dotenv).
