### ISSUE TITLE
Please add stars

### ISSUE THREAD

**Issue by z3t0** [quicklisp/quicklisp-projects#1491]
This is a very basic tool that calculates the total number of stars for a GitHub User.

https://github.com/z3t0/sprint-stars

**Comment by phoe** [comment]
https://github.com/z3t0/sprint-stars/blob/master/stars.lisp#L1

This is going to fail on Lisp implementations that do not have Quicklisp loaded.
Please remove the `QL:QUICKLOAD` lines; the dependencies will be satisfied anyway when the system is loaded via ASDF because your ASD file mentions both DRAKMA and CL-JSON.

**Comment by quicklisp** [comment]
What @phoe says is accurate. You can just take out the `ql:quickload` statements.
