### ISSUE TITLE
Please add simple-petri-net

### ISSUE THREAD

**Issue by phoe** [quicklisp/quicklisp-projects#1542]
simple-petri-net is a library for simulating Petri nets in Common Lisp.

https://gitlab.com/porky11/simple-petri-net

**Comment by Harleqin** [comment]
The README there states that it is not maintained anymore, but superseded by something called "simple-petri-net".  Should the latter be added instead, maybe?

**Comment by phoe** [comment]
Correct. I will edit the main post.

https://gitlab.com/porky11/simple-petri-net

**Comment by quicklisp** [comment]
I can't build it due to the reference to the `ql` package in net.lisp. I think that use could be replaced by a reference to ASDF functions instead and I would be able to make progress.

**Comment by quicklisp** [comment]
This can't be added until the issue with the use of the QL package is resolved.

**Comment by phoe** [comment]
https://gitlab.com/porky11/simple-petri-net/issues/1

**Comment by porky11** [comment]
@phoe I started to hate this library. It's not simple, but overly complicated, messy and buggy.
It works as expected for the most common cases, but some more difficult cases don't work at all.
I even made a fundamental logic mistake: `add-parallel` only takes two arguments.
And besides that, there are some unnecessary utilities, which I would nowadays probably pack into a separate library.

The "simple petri net" is also not really there to generate petri nets.
You don't specify any places. You only specify how the transitions relate to each other using a different logic and the program tries to convert that logic into petri nets. But that doesn't work because petri nets are not suited to represent that logic. That logic is more powerful, and might lead to some weird cases which feel like quantum entanglement. The conversion to perti nets is not allowed, when such cases might occur. It's only converted to perti nets to avoid such cases and allowing simulition.

Some time ago I created a [new petri net simulator](https://gitlab.com/porky11/pns) in C, which should be pretty efficient and only has the core features, so if you want it in common lisp, it might be a good idea to use FFI. I also wrote a few tools in rust for working with real petri nets.
And recently started rewriting the logic used for the `simple-petri-net` package, because as stated in the documentation of `simple-petri-net`, my logic has benefits over real petri nets, even if I have to convert it into petri nets and disallow some cases to simulate it.
I'm calling my logic [flow net](https://gitlab.com/porky11/flow-net) now. The language and the basic logic of parallel and alternative paths is now less related than before.
