### ISSUE TITLE
Please add CLSpec

### ISSUE THREAD

**Issue by sufyanadam** [quicklisp/quicklisp-projects#1901]
CLSpec provides RSpec-like syntax for writing tests.

https://github.com/sufyanadam/CLSpec (MIT License)

**Comment by phoe** [comment]
There is no ASDF system definition in the repository.

**Comment by phoe** [comment]
What are the benefits over already existing test frameworks, including https://github.com/ivankocienski/lspec ?

**Comment by sufyanadam** [comment]
Added ASDF definition.

Benefits: Simpler syntax, small, attempts to respect the principle of least surprise.

Just wanted to make it easier to include in projects where I'd want to write tests. Something like `gem install rspec`. So `quicklisp:install clspec` would be nice, then I could run my test file with something like `sbcl --script my-spec.lisp`, rather than cloning the whole repo or referencing relative paths on my machine.

**Comment by digikar99** [comment]
Erm, are you using `cl-user` package? - I didn't see a `defpackage` form.

Are you aware of `ql:*local-project-directories*`? Also [ultralisp](https://ultralisp.org)?

What is your lisp workflow?

**Comment by sufyanadam** [comment]
@digikar99 thanks for those, I wasn't aware of those.

My lisp workflow is constantly being redefined as I try to learn how to use it. Currently I'm just trying to see if I can write a `script-spec.lisp` file which defines test cases for functions I'd like to write, which I then run by doing `sbcl --scipt SPEC-FILE.lisp`

**Comment by phoe** [comment]
Do you use SBCL from the command line, instead of using an interactive toolkit providing you with a Lisp REPL and file-loading/system-loading/recompiling capabilities, such as silme/sly/slimv/vlime? The latter is a vastly superior option than trying to invoke the Lisp compiler from shell every single time; see [Little Bits of Lisp](https://www.youtube.com/playlist?list=PL2VAYZE_4wRJi_vgpjsH75kMhN4KsuzR_) for an example video series that uses those.

**Comment by digikar99** [comment]
I see. 

Lisp workflow is indeed quite a bit different from other languages - IMO, https://www.youtube.com/watch?v=3GEAINRCbJ4 is a nice illustration - especially once you start doing multifile projects. You simply "load" your system, and tinker around; rather than the edit-(compile-)-run-debug cycle being applied to files, it gets applied to functions/macros/other constructs one at a time. For the time being, if you'd want to avoid emacs / [portacle](https://portacle.github.io/), you might want to try [atom slima](https://atom.io/packages/slima). I'm not sure if you are aware of [Lisp Cookbook](http://lispcookbook.github.io/cl-cookbook/) as well - so just dropping it by. 

Have fun learning around!

PS: I haven't found the time to review [Munro](https://www.youtube.com/c/NeilMunro/videos)'s recent videos on ASDF and Packages (or any other videos), to see whether they illustrate SLIME better than that.

**Comment by sufyanadam** [comment]
Thanks @phoe !  My current (learning) workflow looks like this:

I like a test driven development workflow as it helps me learn better, so I try to define a test file, which I then run using `M-x compile` (which I've bound to F5 lol). 
 
<img width="833" alt="Screenshot 2020-09-13 at 13 05 16" src="https://user-images.githubusercontent.com/1106558/93027463-d2a8ea00-f5c1-11ea-8b36-227409d8733d.png">

When I added `(defpackage)` forms it broke things so I took it out until I learn enough about it to put it back it.

Thank you for the resources, they're _VERY_ helpful for someone on a journey like this!

@digikar99 Thanks for the links, they're awesome. Also, I HODL emacs 😄

**Comment by phoe** [comment]
I usually run tests from the REPL via `asdf:test-system`; that is usable once you have defined an ASDF system with a meaningful test operation. All contemporary test frameworks are hookable this way, and most Common Lisp programmers are used to testing Lisp systems this way

I highly suggest that you learn one of them and how to integrate them with ASDF that way before you submit a test framework of your own to Quicklisp.

Example, with `portable-condition-system` downloaded via Quicklisp and a large chunk of test output removed for clarity:

![Zrzut ekranu z 2020-09-13 22-19-56](https://user-images.githubusercontent.com/15045546/93027729-44f3eb80-f60f-11ea-8643-08884a8b4b5c.png)

**Comment by sufyanadam** [comment]
Thanks @phoe , that is helpful!

**Comment by sufyanadam** [comment]
@digikar99 Thanks! Munro's videos seem to be just what I needed!
