### ISSUE TITLE
Please add ec2-price-finder

### ISSUE THREAD

**Issue by chaitanyagupta** [quicklisp/quicklisp-projects#2018]
https://github.com/chaitanyagupta/ec2-price-finder

EC2 Price Finder helps one quickly find the cheapest EC2 instance that they need across multiple AWS regions.

Go here to see it in action: https://ec2-price-finder.lisper.in/

This is an end user application rather than a library, and I am not sure if its a good idea to add it to quicklisp. If not, please feel free to close the issue.

**Comment by phoe** [comment]
I think it would be a better idea if you separated this system into two systems: a library (that exports the functions for finding the EC2 instance and therefore can be used from the REPL) and a web frontend (that makes use of that library).

Then the library would IMO be 100% good for inclusion into Quicklisp since it'll be directly useful for other people, and your original question would shink in scope to only cover the web frontend (that could be included even as a simple working example of a Lisp web application).

**Comment by phoe** [comment]
Your `loader.lisp` file already seems to implement the library part; I think that if you separate this into a separate package and system and use them in the "web" part, then both parts should be good.

**Comment by chaitanyagupta** [comment]
Yes the library part more or less exists. If I were to export the relevant symbols that would allow this to be used as a library instead of creating two different systems and packages (too much overhead for my comfort), would that be good enough?

**Comment by phoe** [comment]
The main downside would be the fact that people who only want to use the library part would be required to load hunchentoot, spinneret, easy-route, and lass, even if they don't need or care for those systems.

**Comment by chaitanyagupta** [comment]
No doubt that is true. However I intend to make a few more enhancements to this and the internal interfaces are a little fluid at the moment - breaking this up into two systems would bring in additional overhead that I don't want to deal with right now. That is why the original question - would a web application be appropriate to include in quicklisp.

Exporting the library symbols though works fine for me, as it does not get in my way of making changes/refactoring the design. So I am perfectly ok with doing that.
