### ISSUE TITLE
Please, add docs-builder

### ISSUE THREAD

**Issue by svetlyak40wt** [quicklisp/quicklisp-projects#2086]
Source is here: https://github.com/40ants/docs-builder

This project defines a generic interface for building documentation for ASDF systems. And it is used by github action [build-docs](https://github.com/40ants/build-docs) to update gh-pages branch on the GitHub.

**Comment by quicklisp** [comment]
Failure log here: http://report.quicklisp.org/2021-09-17/failure-report/docs-builder.html

**Comment by svetlyak40wt** [comment]
The issue should be fixed in https://github.com/40ants/docs-builder/commit/d969b102fa462553068914377b991930914220fc commit.

**Comment by quicklisp** [comment]
I'm afraid not. Quicklisp is not part of the build environment and cannot
be a dependency.

**Comment by phoe** [comment]
If you *really* need to be able to reference the Quicklisp package in your code, you can use a workaround to access the package at load-time instead of referring to it or its symbols at compile-time. See e.g. https://github.com/phoe/quicklisp-quackload/blob/7a99a59bff8f7d24d3bf85d7b148e7c42e9fef90/quicklisp-quackload.lisp#L77-L81 for a very small example.

(Goodness, of all the Lisp systems I ever wrote, I never expected to be able to refer to `quackload` in any meaningful discussion...)

**Comment by svetlyak40wt** [comment]
Is it possible to rely on uiop:symbol-call?

**Comment by svetlyak40wt** [comment]
Ok, I've switched to uiop:symbol-call: https://github.com/40ants/docs-builder/commit/5720a67076cf2eec9b1747177ff76803f74192bc

@quicklisp please, recheck.
