### ISSUE TITLE
cl-myriam moved over to codeberg

### ISSUE THREAD

**Issue by ariSunz** [quicklisp/quicklisp-projects#2194]
cl-myriam, added in commit f7116ce7c3e0095446f2f4df7d63dc66861cc0ef and previously hosted in Gitlab (https://gitlab.com/ariSun/cl-myriam) will be moving over to Codeberg (https://codeberg.org/arisunz/cl-myriam), please update this info if possible

Thanks in advance!

**Comment by quicklisp** [comment]
Failure log here: http://report.quicklisp.org/2022-09-26/failure-report/cl-myriam.html

**Comment by phoe** [comment]
The foreign function is defined here - 
https://github.com/orivej/pzmq/blob/master/c-api.lisp#L629-L631

Asking because it seems that cl-myriam's test suite actually calls into 
ZeroMQ foreign code at compilation time at 
https://codeberg.org/arisunz/cl-myriam/src/branch/main/tests/run.lisp#L11-L12 
- which makes the presence of libzmq a compile-time dependency of cl-myriam.

Xach, do you actually have libzmq installed on debian as a foreign 
dependency of pzmq?

**Comment by ariSunz** [comment]
Yeah my bad, libzmq is a hard dependency for messaging in cl-myriam to work at all

**Comment by phoe** [comment]
Still, it should be a hard dependency of pzmq, since cl-myriam should be able to depend on pzmq already providing all the necessary build-time functionality.

(An actual, proper fix would be to replace these aforementioned `setf` calls with `defvar`, because `defvar` will not evaluate the value forms at compile-time. Maybe someone with a codeberg account can suggest that.)
