### ISSUE TITLE
Please add nytpu.lisp-utils

### ISSUE THREAD

**Issue by nytpu** [quicklisp/quicklisp-projects#2300]
A collection of miscellaneous standalone utility packages.

Source code: https://git.sr.ht/~nytpu/nytpu.lisp-utils
License: Mozilla Public License 2.0
Has a README and some documentation (primarily docstrings in the source code, but very extensive).  The ASDF system definition has all the requisite metadata. On x86-64 Linux and SBCL, it seems to build without warnings when using `:verbose t` and after removing the system's FASLs from `~/.cache/common-lisp`.

**Comment by phoe** [comment]
Quicklisp-unrelated nitpick: https://git.sr.ht/~nytpu/nytpu.lisp-utils/tree/master/comment-sexps.lisp should respect [`*read-suppress*`](http://www.lispworks.com/documentation/lw60/CLHS/Body/v_rd_sup.htm). Otherwise, reading stuff like `#; #s(foo)` with `foo` not defined as a structure or `bar::baz` with package `bar` not defined or `quux:fred` with symbol `fred` not external in package `quux` will signal an error.

**Comment by nytpu** [comment]
@phoe By “respect” `*read-suppress*`, I assume you mean bind `*read-suppress*` before calling `read`? I just updated it to do that now, seems to work fine; but I'm not an expert in the reader so perhaps you meant something else regarding it. Thanks for pointing it out though!

**Comment by phoe** [comment]
Yes, all is good now. Thanks!
