### ISSUE TITLE
plain-odbc

### ISSUE THREAD

**Issue by francogrex** [quicklisp/quicklisp-projects#84]
Plain-odbc is a nice library that enable CL to efficiently interact with databases like oracle, sqlite etc through odbc. It works well on ECL and SBCL and possibly all other implementations. It may be good to add it to the list of quicklisp libraries. Site at: common-lisp.net/project/plain-odbc/ 
Regards.

**Comment by elliottjohnson** [comment]
Sorry to revive an old thread, but I thought it appropriate.  What are your thoughts on using a more maintained (but probably not "official") version of plain-odbc like https://github.com/hjudt/plain-odbc  The current version in quicklisp is plagued by warnings about cffi bare struct references and it looks like hjudt has done some level of maintenance to make it more comfortable to use.

**Comment by luismbo** [comment]
https://github.com/hjudt/plain-odbc at least does compile on SBCL. @elliottjohnson do you know whether the original author of plain-odbc has been approached to perhaps merge these fixes?

**Comment by elliottjohnson** [comment]
> https://github.com/hjudt/plain-odbc at least does compile on SBCL. @elliottjohnson do you know whether the original author of plain-odbc has been approached to perhaps merge these fixes?

I do not.  The last updates I saw to the SVN were over a decade ago.  I'll send an email and see if I get a response and follow up here

**Comment by phoe** [comment]
You might prefer to open a new issue on `quicklisp-projects` once you are sure that you have found a maintained version and you want to include it in QL over the old version.

**Comment by elliottjohnson** [comment]
Well it's been over a year and 8 months since I first commented.   I'll give Roland a week to respond.

**Comment by elliottjohnson** [comment]
@raverkamp I contacted your old Google mail account, but thought I'd include you here in case you are interested.

**Comment by elliottjohnson** [comment]
I got a response from Roland:

`Hello Elliot,
sorry for the delay.
As you already know I no longer maintain plain-odbc. About about 2
years ago Harald asked me if I mind that he is the new maintainer.
This was OK for me.
He told me that he wanted to maintain it just for his own use cases.

I have not done any Lisp programming for some years.

Best regards,
Roland`

I'll start a new topic to update to the new repository.

**Comment by luismbo** [comment]
@elliotjohnson I propose we do something about the common-lisp.net repository, though. @hjudt are you still interested in maintaining plain-ODBC? What would you like to do with the common-lisp.net project?

**Comment by hjudt** [comment]
I've fixed this so far that it was still working with the latest quicklisp state. I needed it because there was no proper and easy way to fetch data (including CLOBs) from Oracle databases. It does not have a memory-efficient way to handle large selects unfortunately.
Then this plain-odbc was removed from and re-added to quicklisp for reasons I do not know and have not pursuit to discover. It is no longer in quicklisp.
Now I don't know if it is actually working; probably it would need to be updated to a newer version of unixODBC or similar sooner or later. I found [dbd-oracle](https://github.com/hjudt/dbd-oracle), fixed it to work with multi-threading and used this. It has its own problems though like not being able to select clobs.

If there are still users of this library and there is no one else stepping up as maintainer, then I can still try to keep it working for some while. But I am no longer using it myself.

**Comment by luismbo** [comment]
I propose we (@hjudt, @elliottjohnson and I) take up maintainership of the plain-odbc project on common-lisp.net and point quicklisp there. Unless you disagree, I'll go ahead and ask the c-l.net the admins to assign those permissions to us. Do you have common-lisp.net accounts?

**Comment by hjudt** [comment]
That is fine. I believe I do not have a common-lisp.net account, can you tell me how to obtain one?

**Comment by phoe** [comment]
You can ask Erik Huelsmann for one - he's available at `#common-lisp.net` on Freenode.

**Comment by luismbo** [comment]
@hjudt, @elliottjohnson my e-mail address is loliveira at common-lisp.net. Please drop me a line and I'll get the ball rolling wrt the common-lisp.net project.
