### ISSUE TITLE
Please add trivial-documentation

### ISSUE THREAD

**Issue by eugeneia** [quicklisp/quicklisp-projects#974]
Trivial-documentation extracts documentation from a running Lisp image: https://github.com/eugeneia/trivial-documentation

**Comment by quicklisp** [comment]
Can you please make sure the system file has all of :author, :license,
and :description?

**Comment by eugeneia** [comment]
Whoops, fixed!

**Comment by quicklisp** [comment]
Thanks.

When I try to build, I get an error: Package SB-INTROSPECT does not
exist.

This usually happens because slime automatically loads sb-introspect,
but my build environment starts from a (mostly) clean slate.

To get it to build for me, can you please add sb-introspect as a
dependency?

(Is this project SBCL-only, or is sb-introspect conditionalized?)

**Comment by eugeneia** [comment]
> (Is this project SBCL-only, or is sb-introspect conditionalized?)

Its "sb-introspect conditionalized". I have added a conditionalized dependency:

```
  :depends-on ("closer-mop" #+sbcl"sb-introspect"))
```
