### ISSUE TITLE
Please add UFO

### ISSUE THREAD

**Issue by ta2gch** [quicklisp/quicklisp-projects#984]
UFO is a Roswell Script Manager.
https://github.com/ta2gch/UFO
thanks!

**Comment by quicklisp** [comment]
I don't really understand what this project does. Is there any way to add more info to the README about what it is and what it is for?

**Comment by ta2gch** [comment]
I rewrote the README. Would you look again?

**Comment by guicho271828** [comment]
@xach, in order to understand the importance of UFO you also need to understand roswell scripts.

The infrastructure provided by roswell is something like follows:

1. Some quicklisp projects, like clack, caveman, whatever, may contain several .ros scripts in there repo. While the standard lisp files provides the functionality as a library reusable from the other lisp applications, ros scripts are the recipes bundled to the library and provides a direct command line interface from the shell.
2.  `roswell install clack` downloads clack from quicklisp (as normally done by ql:quickload) and make it available to asdf, but also detects the ros scripts in the repo, and install the scripts in user-wide, and the command `clackup` becomes available directly from the shell. Consider my case of quicklisp-project-submission and the pullreq from @snmsts https://github.com/guicho271828/quicklisp-project-submission/pull/1 . 

>    by 'ros install quicklisp-project-submission' you'll get ~/.roswell/bin/qps that'll just load this library and call '(qps:submit)'

3. finally, UFO. UFO installs ros scripts from pastebin or gist or whatever, instead of searching from the quicklisp repository.

**Comment by quicklisp** [comment]
When I try to compile, I get:

    Package ROS does not exist.

That's in addon.lisp.

**Comment by ta2gch** [comment]
It was fixed to use the `uiop:run-program` instead of `ros:roswell`. at latest commit (b17105f7dfef0b5612bb58065ed04eddf5c32ec0)

Please retry it. Thank you.

**Comment by quicklisp** [comment]
Now I get `Package QL does not exist`. I think you could just use the lower-level ASDF functions to get the same effect.

**Comment by ta2gch** [comment]
Thank you for your advice.
Now, I fixed, ufo use `asdf:system-source-directory` instead of `ql:where-is-system`.

Would this be okay?

**Comment by quicklisp** [comment]
It works now, thank you.

**Comment by ta2gch** [comment]
Thank you! :)
